---
# handlers file for .
- name: Restart Postgresql
  systemd:
    name: postgresql
    state: restarted

- name: Start Postgresql
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Enable Postgresql
  systemd:
    name: postgresql
    enabled: yes

- name: Restart sonar
  service:
    name: sonar
    state: restarted

- name: Start sonar
  service:
    name: sonar
    state: started
    enabled: yes